- doc/homepage.ipynb
- examples/user_guide/Gridded_Data.ipynb
- examples/user_guide/Introduction.ipynb
- examples/user_guide/Plotting.ipynb
- examples/user_guide/Statistical_Plots.ipynb
- examples/user_guide/Streaming.ipynb
- examples/user_guide/Subplots.ipynb
- examples/user_guide/Viewing.ipynb
- holoplot/__init__.py
- holoplot/dask.py
- holoplot/intake.py
- holoplot/pandas.py
- holoplot/streamz.py
- holoplot/tests/testcharts.py
- holoplot/tests/testdefaults.py
- holoplot/tests/testpatch.py
- holoplot/xarray.py
As discussed in https://github.com/pyviz/holoplot/issues/14 and https://github.com/pydata/xarray/issues/2199 this PR renames the API from .plot to .holoplot to avoid completely overriding the existing pandas/xarray APIs.
> Renamed API from .plot to .holoplot

- .travis.yml
Means hvplot will keep using the same version of pyctdev that it's using currently, rather than some potentially disruptive dev releases before the next main release.
> Switch to pyviz main channel for pyctdev on CI

- hvplot/converter.py
- hvplot/tests/testgeo.py
Closes #82 
I'm not sure where to document this behavior but the goal was to only have defaults be a little more helpful so it should just do what is expected with whatever is given be it a proj4string, a cartopy.crs or a ds.attr name.
> Add crs from ds if possible

- hvplot/__init__.py
- hvplot/converter.py
Couldn't figure out color_index / size_index though because the underlying hv.Labels encounters some issue I've never seen before...
```
import holoviews as hv
hv.extension('bokeh')
np.random.seed(9)
data = np.random.rand(10, 2)
text = [chr(65+i) for i in range(10)]
df = pd.DataFrame(data)
df.columns = ['x', 'y']
df['text'] = text
df['color'] = range(len(df))
df.hvplot.labels('x', 'y', 'text', c='color')
hv.Labels(df, ['x', 'y'], ['text', 'color']).options(color_index='color')
```
> Add labels functionality

- examples/user_guide/Geographic_Data.ipynb
- hvplot/converter.py
In https://github.com/pyviz/geoviews/issues/230 we worked out that the current behavior of always projecting all the data ahead of time before applying rasterize/datashade operations on it can be very suboptimal because it can result in very long initialization times. This PR disables this default behavior and instead adds an explicit ``project`` keyword argument to enable it.
> Add explicit project kwarg

- examples/user_guide/Viewing.ipynb
The hvplot.display function was removed because ``display`` is a global in IPython.
> Fixed reference to display function

- .gitignore
- .travis.yml
- doc/conf.py
- setup.py
After 0.5.0 of nbsite, evaluated notebooks live in `/doc` next to their dynamically generated `.rst` files. Lines are added to `.gitignore` to prevent accidental checking in of these files. Note that it is sometimes desirable to check in `doc/*.rst` files but it is preferable to generate them from notebooks. The workflow for re-evaluating a notebook and regenerating it's html is:
```bash
$ rm builtdocs/user_guide/Plotting.html
$ rm doc/user_guide/Plotting.ipynb
$ nbsite build --what=html --output=builtdocs
```
Upload the entire contents of `./builtdocs` to your server, or `gh-pages` branch to refresh your website.
> Updating to use nbsite 0.5.0

- hvplot/__init__.py
- hvplot/converter.py
First cut at addressing https://github.com/pyviz/hvplot/issues/130
> Added support for RGB plots

- hvplot/__init__.py
- hvplot/converter.py
Pretty much just added this option in to `_kind_options`, made sure the converter would pass it if specified, and copied relevant docs from holoviews.
Now you can do this:
> Add min_count option for hexbin plots

- hvplot/converter.py
Needs: https://github.com/pyviz/holoviews/pull/3517
> Add clabel

- examples/user_guide/Geographic_Data.ipynb
- hvplot/converter.py
Addresses https://github.com/pyviz/datashader/issues/766 . @philippjfr , not sure if you'd want to allow *only* list types, or any sequence as here.  An alternative to this PR would be to change param.Tuple to coerce inputs to tuples in general, but that does cut down on detecting some genuine error conditions, so I made this more conservative PR instead.
> Allow list types for xlim,ylim tuples

- hvplot/converter.py
- hvplot/tests/testcharts.py
When plotting heatmap without arguments it now defaults to treating the dataframe as an array where the columns are the x-values and the index the y-values. 
Fixes https://github.com/pyviz/hvplot/issues/188
> Handle heatmap rendering as array

- hvplot/converter.py
- hvplot/tests/testcharts.py
Closes #241 
Not quite sure if this is possible with a dask dataframe.
> Only include numeric columns by default if available in data

- hvplot/converter.py
- hvplot/tests/testgridplots.py
https://github.com/pyviz/hvplot/issues/155
examples https://anaconda.org/ahuang11/test_attr_labels
I tried mimicking new line if label too long, but I don't think bokeh supports '\n'
I'm happy where it is now I think.
> Label from attributes

- hvplot/converter.py
- hvplot/tests/testcharts.py
Closes #121 
Also includes a kwarg to turn off this sorting in case it is undesirable. For now I am specifically only doing this for pandas objects because sorting for streamz is a very bad idea, and dask could also be strange. I think starting with pandas will at least be an easier change to default behavior, then if we want to expand it, that will be easy enough.
> Sort by date by default when using pandas objects

- hvplot/converter.py
- hvplot/tests/testgridplots.py
Closes #261 
The last commit in this PR makes the warning only show if the user explicitly sets `attr_labels` to `True`. Not sure whether or not that change is acceptable. But I kept the commit separate so that it is easily revertable if people don't like that idea.
> Fix label for xr.Dataset

- hvplot/tests/testutil.py
- hvplot/util.py
After #173 went in, I realized that there is more info in the coords attrs that can be used to set better defaults. 
This PR:
For reference, this is the output of the same call on master:
> Using attrs to set default x and y for gridded outputs

- hvplot/converter.py
- hvplot/tests/testutil.py
- hvplot/util.py
Closes #54 
Allows using derived datetime for xarray objects
```python
ds = xr.tutorial.open_dataset('air_temperature')
plot = ds.hvplot.violin(y='air', by='time.month')
plot
```
```python
ds.mean(dim=['lat', 'lon']).hvplot(by='time.hour')
```
```python
data.hvplot.scatter(y='air', x='time.dayofyear', by='time.year')
```
> Adding derived datatime for xarray

- hvplot/converter.py
- hvplot/tests/testoperations.py
Closes #204 
This is kind of a half-solution. It just turns off the hover when datashade is true if the user doesn't specifically ask for it.
> If datashade=True then hover should be false by default

- hvplot/converter.py
- hvplot/tests/testcharts.py
- hvplot/tests/testoperations.py
Closes: #226 
Note that this PR also fixes some instances of hvplot altering the input data.
```python
import holoviews as hv
from bokeh.sampledata.autompg import autompg
hv.extension('bokeh')
autompg.hvplot.scatter(x='mpg', y='yr', c='yr', datashade=True, dynspread=True)
autompg.hvplot.scatter(x='mpg', y='yr', c='yr', rasterize=True, y_sampling=1, x_sampling=1)
```
> Allow datashade/rasterize even when c is same as x or y

- hvplot/converter.py
- hvplot/tests/testoperations.py
The axis zoom was happening after datashading when it should have been happening before.
Closes: #177 
```python
pd.DataFrame(y).hvplot(datashade=True, xlim=(0, 20000))
```
Before this PR:
After this PR:
> Fixing lim should be used as range when datashading

- hvplot/networkx.py
- hvplot/tests/testnetworkx.py
Closes: #223 
Using example from issue:
Not sure how to test.
> Fixing color order should match node order

- hvplot/__init__.py
- hvplot/converter.py
- hvplot/tests/testcharts.py
- hvplot/util.py
Closes: #278
I was experimenting with this simulated dataset:
```python
time_df = pd.DataFrame({
'time': pd.date_range('1/1/2000', periods=5*24, freq='1H', tz='UTC'),
'temp': np.sin(np.linspace(0, 5*2*np.pi, 5*24)).cumsum()})
time_df.hvplot(x='time.hour', by='time.dayofweek')
time_df.hvplot.heatmap(x='time.hour', y='time.day', C='temp')
```
> Derived datetime for tabular data

- hvplot/converter.py
- hvplot/tests/testgridplots.py
- hvplot/tests/testoptions.py
- hvplot/util.py
https://github.com/pyviz/hvplot/issues/205
The centering is based off all time step / all dimensions.
```
ds = xr.tutorial.open_dataset('air_temperature')
da = ds['air']
da_anom = da - da.mean()
da_anom.hvplot('lon', 'lat')
```
> Determine whether data is divergent and use a RdBu colormap / center clim

- hvplot/plotting/core.py
- hvplot/tests/testpanel.py
- hvplot/tests/testutil.py
- hvplot/util.py
- setup.py
NEW: Replacing #279 and updating to accept widgets as well as parameters.
This PR makes it possible to build GUIs by passing parameters instances directly into the hvPlot methods. Combined with Panel this makes it very easy to build complex GUIs.
```python 
import panel as pn
from bokeh.sampledata.iris import flowers
cols = list(flowers.columns[:-1])
x = pn.widgets.Select(name='x', value='sepal_length', options=cols)
y = pn.widgets.Select(name='y', value='sepal_width', options=cols)
kind = pn.widgets.Select(name='kind', value='scatter', options=['bivariate', 'scatter'])
by_species = pn.widgets.Checkbox(name='By species')
color = pn.widgets.ColorPicker(value='#ff0000')
@pn.depends(by_species, color)
def by_species_fn(by_species, color):
return 'species' if by_species …
```
> Made hvplot API dynamic by accepting parameter/widget instances

- examples/user_guide/Gridded_Data.ipynb
- examples/user_guide/NetworkX.ipynb
- examples/user_guide/Plotting.ipynb
- examples/user_guide/Subplots.ipynb
Removed some unused imports.
Wasn't sure if it's ok to remove the intake import or not in Plotting.ipynb?
-----
Ignore deliberate side effect imports:
```
diff --git a/tox.ini b/tox.ini
index 8ab9e46..25834a4 100644
--- a/tox.ini
+++ b/tox.ini
@@ -73,7 +73,8 @@ norecursedirs = doc .git dist build _build .ipynb_checkpoints
-
+nbsmoke_flakes_to_ignore = .*hvplot\..* imported but unused.*
+
[flake8]
include = *.py
```
```
(nbsdev) D:\code\pyviz\hvplot>pytest -v --nbsmoke-lint --nbsmoke-lint-debug examples
=============================================================== test session starts ================================================================
platform win32 -- Python 3.6.8, pytest-4.4.1, py-1.8.0, pluggy-0.9.0 -- d:\venvs\nbsdev\scripts\python.exe
cachedir: .pytest_cache
rootdir: …
```
> Removed some unused imports

- hvplot/converter.py
- hvplot/tests/testgridplots.py
This came up in the context of data that is being read from thredds.
> Adding a max size for checking symmetry

- hvplot/converter.py
> Don't count by if subplots

- hvplot/__init__.py
- hvplot/tests/testplotting.py
```python
pd.options.plotting.backend = 'hvplot'
data = np.random.normal(size=[50, 2])
df = pd.DataFrame(data, columns=['x', 'y'])
df.plot(x='x', y='y')
```
> Exposing plot at top level

- hvplot/plotting/core.py
- hvplot/tests/testpanel.py
This is kind of a follow on to the widget work in #331 and #323 this lets the groupby widget that hvplot creates get through even when other widgets options are used. 
```python
import geoviews.tile_sources as gvts
import panel as pn
base_map = pn.widgets.Select(options=list(gvts.tile_sources.keys()), value='EsriImagery')
data = xr.tutorial.load_dataset('air_temperature').air
pn.Column(
base_map,
data.hvplot.contour(geo=True, tiles=base_map, widget_type='scrubber', 
widget_location='top', widget_layout=pn.Row,
levels=10, cmap='reds', line_width=2))
```
> Stop swallowing groupby widgets when passing widgets

- hvplot/converter.py
I've grepped for `params()` and `get_param_values()` so far...I'll look for other uses now.
> Updated use of param API in converter.py

- examples/datasets.yaml
Quick PR needed to make sure the download from S3 of `airline_flights.parq` can be reliably executed by intake.
> Specifying S3 region for airline_flights.parq

- hvplot/converter.py
Fontscale keyword was added so that hvplot can also handle this keyword. This should solve #395 . 
Also added documentation about fontscale in docstring of class HoloViewsConverter(object).
I didn't add fontscale to the __init__() of class HoloViewsConverter(object), but it falls now under the **kwds. If this still needs to be done, please let me know.
Tested some simple plots myself in Jupyter, that seemed to work. Didn't add any formal tests.
> add keyword fontscale (solving #395)

- hvplot/__init__.py
Work in progress PR to address #405.
> Added support of tab completion via signature

- hvplot/converter.py
* 'title_format' triggers a deprecation warning in
holoviews.plotting.plot.DimensionedPlot._format_title
> change plot_opts['title_format'] to plot_opts['title']

- hvplot/util.py
When using dask an empty assign still adds significant overhead.
> Do not apply empty apply

- examples/user_guide/Geographic_Data.ipynb
- hvplot/converter.py
- hvplot/tests/testgeo.py
As jsignell suggested, string crs probably isn't too useful since you need to pass arguments in most cases if it's not degree latitude/longitude crs so I didn't support that, but I think being able to use a simple string for `projection` is useful.
https://github.com/holoviz/hvplot/issues/363
> Support string projection kwd

- doc/user_guide/index.rst
- examples/user_guide/Interactive.ipynb
- hvplot/cudf.py
- hvplot/dask.py
- hvplot/interactive.py
- hvplot/pandas.py
- hvplot/xarray.py
Implements interactive API as described in https://github.com/pydata/xarray/issues/3709.
Depends on https://github.com/holoviz/holoviews/pull/4578
> Implement interactive API for all data backends

- examples/user_guide/Interactive.ipynb
- hvplot/cudf.py
- hvplot/dask.py
- hvplot/interactive.py
- hvplot/pandas.py
- hvplot/xarray.py
Interactive.ipynb looks great! Here I've made mostly minor cleanups and clarifications. The biggest addition is a Panel app at the very end. I think it's important to show that .interactive isn't a dead end, i.e. that it can be reconfigured and used in a larger app the same way as interact() can. Remaining issues:
> Made a pass over the Interactive user guide

- .github/workflows/test.yaml
- hvplot/converter.py
- hvplot/tests/teststreaming.py
This allows external code to pipe data through hvPlot without instantiating a `streamz.DataFrame` instance. Very useful when you have some updating datasource.
> Add support for passing in explicit HoloViews stream

- hvplot/networkx.py
Keeping tuple attributes confuses the data extensions.
Fixes https://github.com/holoviz/hvplot/issues/419
> Do not keep tuple NetworkX attributes

- doc/index.rst
Disables the warning on the homepage (when built with latest nbsite).
> Disable interactivity warning on homepage

- hvplot/converter.py
- hvplot/tests/testcharts.py
- setup.py
Any `by` columns were not passed through the derived column processing which meant it was not possible to use datetime accessors.
> Apply not found logic to 'by' columns

- examples/user_guide/Plotting.ipynb
I think this should be `.hist()` in the docs.
> 📝 `.histogram()` function does not exist

- hvplot/util.py
This change allows `hvplot.utils.with_hv_extension` to preserve function signatures and docstrings, which are currently lost.  Fixes #600.
> preserve function signature and docstring in `with_hv_extension`

- hvplot/plotting/scatter_matrix.py
This adds a new argument that allows the user to specify keyword arguments for the diagonal plots in `hvplot.plotting.scatter_matrix`.  Fixes #599.
> support setting options for diagonal plots in scatter_matrix

- hvplot/converter.py
- setup.py
This PR aims to address #603 by generating default image coordinates when they are missing.
Before the PR, using the example given in #603:
With the PR:
So far I've only thought about the `Dataset` branch, to finish this PR I'll need to handle the `DataArray` case as well.
> Adding default coordinates to Datasets with missing image coords

- examples/reference/pandas/ohlc.ipynb
- hvplot/converter.py
- hvplot/plotting/core.py
> Implement OHLC plot

- README.md
Minor fix to the Github Actions badges to point them to the master branch.
>  Pointed GHActions badges to master branch

- hvplot/interactive.py
- Add `.eval()` method to get current state
- Support numpy ufuncs
- Ensure attribute access is evaluated
> Allow attribute access on ufunc on interactive

- hvplot/converter.py
The current versions and probably the ones before that of holoviews and datashader support doing spread and dynspread on rasterized output, not just datashaded RGB output, but hvplot was mistakenly flagging usage with rasterize as an error. We could check hv and ds versions to find if such a check should be applied, but it seems simpler just to no longer distinguish between rasterize and datashade, since most people nowadays will get a suitably compatible version of Datashader, and for the rest it's an error condition anyway.
> Allow dynspread to be used with rasterize

- hvplot/tests/testgeo.py
Fixes #657 
The code uses PROJ under the hood that matches `'foo'` with a projection named `'Amersfoort'`. Replaced by '`name_of_some_invalid_projection'` which doesn't match and should never match any projection in the future.
> Fix a broken test due to PROJ unexpectedly matching 'foo'

- hvplot/converter.py
- hvplot/tests/testoptions.py
Fixes #656 
Plots based on xarray objects that have scalar coords (e.g. `da.isel(lon=0)`) will get an informative title as one would get with xarray.plot() API. The generated title is equal to xarray's title since internally xarray's formatting utilities are used. This is part of their private API but this code hasn't changed in years.
There are a couple of differences with xarray:
1. If the data has more than two dimensions it will default to a histogram without providing it further hints. In that case xarray.plot() just sets `'Histogram'` as a title, while hvplot() will set the informative title (e.g. `lon = 250`).
2. Whenever widgets are generated to explore the data (groupby op) the title is not changed, it is a title generated by holoviews that is in sync with the widget's values and …
> Add a title to xarray plots with scalar coords

- README.md
- examples/homepage.ipynb
Guide was previously removed. The content provided installation instructions to which I am changing the wording and link to.
The commit that removed the guide: https://github.com/holoviz/hvplot/commit/8d3c7ecbc0ba296ea34d799cc1b069839df7ec56
> Docs - Remove link to 'getting_started'.

- hvplot/converter.py
A RuntimeWarning was emitted by numpy with the following snippet. It was trying to calculate `np.nanquantile` on an empty series in this case.
```
df = pd.DataFrame({'x': [], 'y': [], 'color': []})
df.hvplot(kind='scatter', x='x', y='y', color='color')
```
The only thing I'm unsure of is whether the data variable always has a `size` parameter. In other words, what type of object could `data` possibly be in this function?
> State that the data cannot be symmetric if it's empty

- hvplot/converter.py
PR in preparation of the upcoming support of Matplotlib and Plotly.
`self._dim_ranges['c']` was set to either `clim` if not None or to `(None, None)`. This caused no issue with the Bokeh backend of holoviews, which accepts a `param.Tuple` for `clim` and handles properly when it includes `None`. However both the Matplotlib and Plotly backends accept a `param.NumericTuple` only.
The Bokeh backend used to accept a `param.NumericTuple` only as well, but that was changed in https://github.com/holoviz/holoviews/pull/4383. The right fix might be to add support to whatever the Bokeh backend supports to Matplotlib & Plotly with allowing them to accept a non-numeric tuple for `clim`, but since I don't know what exactly this PR was about I went for the simpler, and hopefully correct, solution.
An …
> Update the default internal value of `clim` to support Matplotlib

- hvplot/__init__.py
If the panel extension is already loaded do not load it a second time, instead simply initialize the selected HoloViews backend.
> Ensure bokeh/panel extension is loaded only once

- hvplot/converter.py
- hvplot/ui.py
This PR is working towards getting the hvPlot UI into a state where we can release it.
> Improving the hvPlot UI

- examples/user_guide/NetworkX.ipynb
- hvplot/networkx.py
- hvplot/ui.py
Added support for [nx.draw_planar convenience function](https://networkx.org/documentation/stable/reference/generated/networkx.drawing.nx_pylab.draw_planar.html) and an example to the User guide.
Wasn't sure how to test this, let me know if I anything else is required :)
> MAINT: Add support for planar layout from NX

- hvplot/sample_data.py
> fix 692: add more imports to try/except import check

- .gitignore
- hvplot/interactive.py
Fixes #697
Needs https://github.com/holoviz/holoviews/pull/5184 to work
> Flatten op_args to be able to find nested widgets

- .github/workflows/test.yaml
As discussed with @MridulS:
* Remove the restore key since the goal is to hit exactly the cache required
* Add the options (e.g. `tests`, `build`, `docs`...) used for `develop_install`. Without that there would be no way to distinguish between two caches used by two different workflows (e.g. tests and docs). It's not perfect though, since sometimes there are some packages that are installed without `develop_install` (e.g. some packages only available with pip). Maybe it'd be a good idea to have the hash of the workflow itself part of the cache key.
> Improve Github Action caching

- examples/reference/pandas/scattermatrix.ipynb
- hvplot/plotting/scatter_matrix.py
This PR adds a reference page for the `scatter_matrix` plots. It also fixes to docstring of this function to reflect the fact that `tools` only support a `list` of tools.
> Add scatter matrix reference

- .github/workflows/test.yaml
By installing importlib_resources, dependency required by the latest tqdm but not declared in its recipe (https://github.com/conda-forge/tqdm-feedstock/pull/114).
> Fix the CI on Python 3.6

- hvplot/converter.py
When creating a figure with `geo=True`, the `scale` argument for `geoviews`-features is currently ignored. According to the documentation and docstrings, this should be supported via setting the `feature` argument to a dictionary in the form of {feature: scale}. 
With this change, the scale argument is forwarded to the `opts` function of the `geoviews` feature class.
```
import hvplot.pandas  # noqa
from bokeh.sampledata.airport_routes import airports
plot = airports.hvplot.points(
"Longitude",
"Latitude",
geo=True,
color="red",
alpha=0.2,
xlim=(-180, -30),
ylim=(0, 72),
tiles="ESRI",
features={"states": "10m"},
)
hvplot.show(plot)
```
> Fix application of the scale argument for geoviews features

- hvplot/converter.py
Exposes options now supported with datashader 0.14 (unreleased) and exposed in HoloViews in 1.14.9 (unreleased).
> Expose datashader line_width and rescale_discrete_levels options

- examples/user_guide/Interactive.ipynb
- hvplot/__init__.py
- hvplot/dask.py
- hvplot/interactive.py
- hvplot/tests/testinteractive.py
- hvplot/xarray.py
Implements functionality requested in https://github.com/holoviz/hvplot/issues/673
```python
from bokeh import sampledata
ticker = pn.widgets.Select(options=['AAPL', 'IBM', 'GOOG', 'MSFT'], name='Ticker')
def stock_df(ticker):
df = pd.DataFrame(getattr(sampledata.stocks, ticker))
df['date'] = pd.to_datetime(df.date)
return df
stock_dfi = hvplot.bind(stock_df, ticker).interactive(width=600)
stock_dfi.head(10)
```
> Add ability to call interactive on bound functions

- setup.py
New tests have been added that rely on xarray being installed, and xarray is indeed an important interface to test part of the test suite. This PR adds it to the `tests` extras.
> Add xarray to the tests extras dependencies

- .github/workflows/test.yaml
- README.md
- setup.py
- tox.ini
I've tried again to add `3.10` in the test matrix, and this time it worked! Installing `pygraphviz` is pretty slow on Mac so I've had to increase the timeout but besides that all is well. This PR also fixes the CI on Python 3.6 and 3.7 by pinning `tifffile`, whose latest recipe isn't correct.
> Add 3.10 in the test matrix and fix it on 3.6 and 3.7

- hvplot/plotting/core.py
- hvplot/tests/plotting/testcore.py
- hvplot/tests/testutil.py
- hvplot/util.py
Fixes #713
Properly one of the simplest ways to support array-like in hvplot.
> Improve array-like handling for x and y inputs

- examples/user_guide/Plotting_Extensions.ipynb
- examples/user_guide/Plotting_with_Plotly.ipynb
To workaround an issue in HoloViews whereby the `load_nb` method of the renderer is not called when the extension is loaded multiple times within a single cell, effectively not loading setting up the Panel Plotly pane correctly.
> Separate plotly extension calls

- CHANGELOG.md
- doc/conf.py
- doc/releases.md
- examples/user_guide/Plotting_Extensions.ipynb
- examples/user_guide/Plotting_with_Matplotlib.ipynb
Use `require.js` vendored by nbsite to display the Plotly figure add the end of the Plotting_Extensions notebook. `require.js` is normally loaded automatically by nbconvert but that happens not to be the case when a notebook is converted via nbsite. Other HoloViews-Plotly plots are rendered via Panel, in a way that doesn't seem to require `require.js`.
> Display the Plotly figure without Panel

- .gitignore
- hvplot/__init__.py
- hvplot/tests/testhelp.py
The help function was not showing the style options of the current backend when `compatibility` wasn't set, instead it was always showing the Bokeh style options.
> Show the right style options with the help function

- .github/workflows/test.yaml
- doc/developer_guide/index.rst
Fixes #790 
Trying a slightly new approach that consists in creating a totally empty conda environment, then setting the channels of this environment only and not globally, and then simply calling `doit/pyctdev` and pure `conda` commands without providing any channels as `-c channel`, just relying on the ones defined at the environment level.
> Update developer install instructions

- hvplot/tests/testoptions.py
One test started to fail after the release of xarray 2022.6.0 a couple of days ago. The title set to a plot made from an xarray object is defined by relying on an internal xarray function, this was added in https://github.com/holoviz/hvplot/pull/659. Apparently something changed in xarray, I actually didn't see any obvious change in the particular function that was called so that may be at another level, anyway the scalar coords displayed in the title are not ordered in the same way after the last release. In the failing test `'y = 0, x = 0, time = 0, band = 0'` was replaced by `'time = 0, y = 0, x = 0, band = 0'`. The former, i.e. the newer title, appears to be more accurate as respecting the order of the coords declared in one of the original DataArray: …
> Update the expected DataSet plot title after xarray `2022.6.0`

- hvplot/interactive.py
- hvplot/util.py
Fixes https://github.com/holoviz/hvplot/issues/797
Instead of bumping the HoloViews pin to a quite recent version, this PR just copies the `flatten` utility from HoloViews to hvPlot.
> Add flatten utility function

- hvplot/converter.py
- hvplot/tests/testoperations.py
Fixes https://github.com/holoviz/hvplot/issues/777
Before https://github.com/holoviz/hvplot/pull/206 the `cmap` style was handled as follows, i.e. when datashader was involved it was set to the default linear colormap:
```python
if cmap is not None:
style_opts['cmap'] = cmap
elif self.rasterize or self.datashade:
style_opts['cmap'] = self._default_cmaps['linear']
```
https://github.com/holoviz/hvplot/pull/206 made hvplot behave more closely to `xarray.plot()` by using a symmetric colormap if the data is found to be divergent. https://github.com/holoviz/hvplot/pull/206 replaced the code that set the colormap to linear, by setting the color bar, to `True` by default:
```python
if cmap is not None:
style_opts['cmap'] = cmap
elif self.rasterize or self.datashade:
plot_opts['colorbar'] = …
```
> Display a color bar when rasterize is enabled

- hvplot/interactive.py
- hvplot/tests/testinteractive.py
- hvplot/tests/testoperations.py
- hvplot/tests/testoptions.py
- hvplot/tests/testoverrides.py
- setup.py
This PR adds various tests to `Interactive`. The aim of these tests is two-fold: cover parts that were untested and better track the underlying logic of `Interactive`. More comments in particular are meant to be added.
Interestingly I wrote these tests first based on the `0.7.3` version of hvPlot, before the support for functions as input was added. The logic at the time was slightly easier to comprehend. When writing the tests I added some utility to inspect calls to the `_clone` method at it seemed central to the way `Interactive` operates. When I finally ran the tests against *master* I had to update these tests, `_clone` is called more than it used too. The logic of `Interactive` has become more difficult to track.
> Add more tests to `Interactive` and some comments

- hvplot/ui.py
Partially fixes #785 (2 and 4)
Indexes are now only added to `x`. For `x` and `y` because they are `param.Selector` needs to have the first value in the object specified, else they are None, which can give problem later on, e.g., when plotting.  
`self._plot` was removed because it is called when triggering `kind` on the next line.
<s>I have added the empty plot. Because when something fails, I think it is wrong to show the last working plot. The current configuration of settings does not output that plot. If people disagree with this, I could remove it from this PR and open another issue/PR to discuss it in. </s>
> Enhancement to Fields tab in explorer

- hvplot/ui.py
Sort of fixes https://github.com/holoviz/hvplot/issues/786
The explorer had a `marker` styling option available that in practice wasn't useful as it was not listing the markers available, in light of the upcoming release this PR simply removes this option.
Handling the styling options is a lot trickier than the other plot options:
- they vary given the selected backend
- they vary given the select kind of plot
- hvPlot for sure doesn't know anything about the values a styling option like `marker` can accept. I don't think HoloViews does either, @jlstevens do you confirm?. And I don't know if the plotting backends have APIs that expose their allowed values.
- there can be many many options to set, in particular for the interactive backends
It seems like there's more thinking and work …
> Remove the marker styling option of the explorer

- hvplot/interactive.py
- hvplot/tests/testinteractive.py
Alternative implementation (https://github.com/holoviz/hvplot/pull/768) to fix https://github.com/holoviz/hvplot/issues/763
The problem in https://github.com/holoviz/hvplot/issues/763 was two-fold:
1. the callback used to update the original pipeline object (`self._obj`, e.g. a DataFrame) was registered every time a new `Interactive` instance was created. Even a small pipeline creates many instances so that led to many calls being made when one of the parameters controlling the input function changed.
2. only the last callback registered was actually updating the right `self._obj` object. Even if all the instances share the same object, setting a new object in the update callback would not lead to that new object being set on all the instances, just on that particular one. This is why in …
> Interactive: only register once the function parameters watchers

- hvplot/interactive.py
- hvplot/tests/testinteractive.py
- tox.ini
This PR fixes some issues observed on the operators implemented by Interactive:
* reversed operators were implemented but the `reverse` info was never passed to the dim transform
* one dunder method was using the wrong operator
* removed `__div__` as it has been removed in Python 3
This PR also makes the test suite fail when an xfail test actually passes (xpass).
> Some fixes to the operators implemented by Interactive

- hvplot/interactive.py
- hvplot/xarray.py
An attempt at adding the docstring for interactive. I have kept the class docstring in the code, but because it is heavily developer-focused, I have removed it when using `?` in a notebook.
> Adding docstring to interactive

- .gitignore
- doc/user_guide/index.rst
- examples/user_guide/Explorer.ipynb
- hvplot/__init__.py
- hvplot/tests/testui.py
- hvplot/ui.py
- tox.ini
Fixes https://github.com/holoviz/hvplot/issues/764 
Fixes #787
@philippjfr  in https://github.com/holoviz/hvplot/commit/87b07b424067c4a413edbf4ab46360915c6a51e3 I've removed the `__new__` methods. They were causing `__init__` to be called twice, which wasn't really an issue as far as I could tell but was for sure undesired. I found no way to fix that by keeping them, so replaced them by a factory class method `from_data` that I use in the `explorer` function. This is a breaking change, which might be fine given that the explorer has been released recently and never documented. If this breaking change is unwanted, I could add a warning when an explorer isn't instantiated with `from_data`, or keep digging to try to fix the issue with `__new__`.
> Make the explorer easier to use

- hvplot/interactive.py
- hvplot/tests/testinteractive.py
Interactive has a `max_rows` parameter that should be passed down to the `pn.pane.DataFrame` object created when the output of a pipeline is a dataframe. This parameter was not passed down the pipeline, which is fixed by this PR.
> Interactive: propagate max_rows

- hvplot/interactive.py
- hvplot/tests/testinteractive.py
I realize Interactive is inefficient as hell and intermediate calculation aren't cached. I think at some point this warrants a rewrite of the execution model inside Interactive. However this PR at least ensures that straightforward copied clones don't re-execute the transforms needlessly.
> Do not re-execute transform on copied clones

- hvplot/converter.py
The docs built failed [here](https://pyviz-dev.github.io/hvplot/user_guide/Gridded_Data.html#rasterizing) as `y` is implicitly set to `['air']`, which was not anticipated in this conditional:
```python
elif ((isinstance(self.y, list) or self.y is None and len(set(self.variables) - set(self.indexes)) > 1) and
self.kind in ('scatter', 'line', 'area')):
```
> Set categorically shaded when there's more than one variable

- hvplot/converter.py
Fixes https://github.com/holoviz/hvplot/issues/823
GeoViews `Feature` objects are already instantiated in Geoviews. These objects are callable, this can be used to set up their options. hvPlot was calling them but not passing any options, making it a no-op. This PR was motivated by a HoloViews issue that led to a warning being emitted on a no-op `.opts` call (https://github.com/holoviz/holoviews/issues/5407)
> Fix HoloViews .opts warning by not calling GeoViews features

- hvplot/interactive.py
- hvplot/tests/testinteractive.py
I think this is reverting to the previous behavior. If not  this example in the docs fail:
Updated a test that I think was expecting the wrong outcome.
> Interactive: no DynamicMap when hvplot kind is not a string

- hvplot/interactive.py
This is to avoid a warning emitted by Panel, there's more details in https://github.com/holoviz/panel/pull/3715.
> Interactive: callback dependent only when parameters found

- doc/_static/custom.css
- doc/conf.py
The dark theme doesn't play well with plots in general, we should for now just support the light theme. The theme switcher was already removed, but the theme wasn't by default set to the light one, so visitors get whatever default theme configured they have.
> Default to the light theme

- doc/developer_guide/index.rst
Addresses
- Fixes #879
- Fixes #880 
- Fixes  #882
> Fixes developer guide

- hvplot/tests/test_links.py
I thought they would not be picked up as the file name is `test_links.py` while the test files in hvPlot are formatted as `testthing.py`, I was wrong, and it appeared this test isn't very robust and fails from time to time.
> Disable the urls test

- .github/workflows/test.yaml
Ush that was a long fight! For some reason the way the latest `mamba` was installed in the workflow led to some DLL import error on Windows. I went one way and tried many different options, until I finally just decided to pin mamba to an older version, and that worked! Really looking forward to libmamba being the default in conda, which hopefully will have better support than mamba for all the things we do!
> CI: fix the test suite on Windows

- hvplot/converter.py
- hvplot/tests/testcharts.py
Fixes #816
With this change, the xarray dataset metadata propagates to `NdOverlay` figures. This will give more descriptive information like the xlabel in the example below, where it before only showed `t`. 
The added `.redim` could be placed on the line above or below, but I can´t think of a reason why one of them is better than the other.
> Ensure that xarray dataset metadata propagates to NdOverlays

- hvplot/converter.py
- hvplot/tests/testgeo.py
- setup.py
Fixes https://github.com/holoviz/hvplot/issues/929
> Add support for rioxarray rasterio and update tests

- examples/getting_started/interactive.ipynb
The ROLLING_WINDOW param was not actually being used in the pipeline, although that was the intention. 
I also changed it to default '1D' to make it consistent with the later visualization. Also because what it was before ('1W') throws an error `ValueError: <Week: weekday=6> is a non-fixed frequency`
> add intended rolling_window param into pipeline

- hvplot/util.py
Fixes https://github.com/holoviz/hvplot/issues/534
In the issue it was suggested to mention GeoViews only. The more robust approach seems to instead declare all the dependencies required by `process_crs`.
> Improve error message mentionning pyproj

- hvplot/ui.py
Fixes #965 
This PR will hide the slider if the value of xlim or ylim equals each other.
> Don't use xlim/ylim slider if start and end values are identical

- hvplot/ui.py
This workaround converts datetime limits to integers to at least get some functionality instead of the error given in https://github.com/holoviz/hvplot/issues/964. 
https://user-images.githubusercontent.com/19758978/202196533-f9af37ab-72a9-4ec0-8684-5b56b953bd8c.mp4
> Add workaround when having axes which are datetime-like

- setup.py
FIxes https://github.com/holoviz/hvplot/issues/970
With the release of Bokeh 3 users started to get Bokeh 3 when installing hvPlot, while it's not compatible with it.
This PR adds Panel as a runtime dependency, as it is actually required by the explorer. It also pins it to `>=0.11.0` as this version of Panel is the first one that added an upper pin to Bokeh.
Alternatively we could have pinned HoloViews to `>= 1.15.0` as it pinned `"panel >=0.13.1"`, however it's just been released 6 months ago. Previous releases of HoloViews pinned `"panel >=0.9.5"` which didn't have the upper pin for Bokeh.
> Add panel pin to ensure Bokeh <3

- setup.py
Not to get the 6.18.0 version from conda-forge, already yanked from PyPI.
> Temporarily pin ipykernel

- hvplot/converter.py
- hvplot/ibis.py
- hvplot/tests/testibis.py
Closes #988 
After this change I can produce a plot from the example in #988. But it seems it does not understand the Timestamp type should be shown as datetime on the x-axis. I will create a separate issue with holoviews for that.
I've created an issue here https://github.com/holoviz/holoviews/issues/5521.
> fix .hvplot for ibis

- hvplot/tests/testutil.py
- hvplot/util.py
This PR makes the `process_crs` more generous in what it accepts and adds tests for the function.
> Let ``process_crs`` try a few approaches before raising error

- hvplot/converter.py
- hvplot/tests/testgridplots.py
Closes #666 
This resolves the MRE in the original issue. I didn't quite get around to adding a test though :grimacing: 
```python
ny, nx = (30, 20)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 2, ny)
coords={'y': ('y', y), 'x': ('x', x)}
foo = xr.DataArray(np.random.rand(ny, nx), dims=['y', 'x'], coords=coords)
foo.hvplot('x', 'y', label='Foo') 
```
> Fix label on unnamed data array

- hvplot/converter.py
- hvplot/ui.py
- setup.py
- Add `param` as a runtime dependency, `>=1.9.0` for when `.param.objects()` was added. It was an oversight not having it explicitly listed in the runtime deps, as it's used directly for the *Explorer*
- Replace usage of `.param.params()` with `.param.objects()`
> Update Param method

- hvplot/interactive.py
- hvplot/tests/testinteractive.py
- Fixes `Interactive.eval()` ensuring it returns the current value (previously it would only ever return the initial value)
- Ensures that unless parameters change we don't re-evaluate the pipeline each time the value is requested by a callback.
> Ensure interactive pipeline is not re-executed needlessly

- examples/reference/pandas/hist.ipynb
- hvplot/plotting/core.py
Closes #998. 
Please note https://github.com/holoviz/holoviews/pull/5540 closes the issue about the non-understandable error message when trying to `hist` categorical data.
In addition, I've added more examples to illustrate what is possible.
Comparing to the plotly documentation there is still a long, long way to go https://plotly.com/python/histograms/.
> improve the hist reference guide

- examples/reference/pandas/bar.ipynb
- hvplot/converter.py
- hvplot/plotting/core.py
Addresses a users comment about limited `bar` documentation and no documentation of `color`. See https://discourse.holoviz.org/t/is-there-a-way-to-add-a-specific-color-to-each-group-in-a-grouped-bar-plot-like-hue-in-seaborns-barplot/5066
Also fixes a few docstring bugs identified when rendering the output of `hvplot.help('bar')` on Discourse.
https://user-images.githubusercontent.com/42288570/224508335-3a1d31b4-64ee-4943-a0ee-591886aa3529.mp4
The main issue is that lots of things does not work for Matplotlib and Plotly backends as they do for Bokeh backend
- #1034 
- #1035 
- #1036 
- #1037 
- #1038 
- #1039
> Improve bar documentation especially for color

- hvplot/converter.py
- hvplot/interactive.py
- hvplot/plotting/scatter_matrix.py
- hvplot/tests/testinteractive.py
- hvplot/tests/testutil.py
- hvplot/util.py
In the next release of Holoviews 1.16, this will raise an error:
``` python
pd.DataFrame([1, 2, 3, 4]).interactive()
```
Fixes a known issue first shown here https://github.com/holoviz/hvplot/issues/918 and are related to https://github.com/holoviz/hvplot/pull/932.
Other places that use `hv.Dataset` are here. I don't know if they will error:
> Transform columnar data for interactive

- hvplot/util.py
...when an intake Transform is local instead of formally installed
PR for https://github.com/holoviz/hvplot/issues/1051
> tiny fix so hvplot can be used with intake

- doc/conf.py
Updates tracking ID to the new GA4 since the old Universal Tracking is shutting down and we haven't yet decided to move away from GA.
> Update to Google Analytics4

- hvplot/converter.py
- hvplot/plotting/core.py
- hvplot/tests/testinteractive.py
Simon spotted one test that would failed with https://github.com/holoviz/param/pull/729, this PR fixes it.
I've also fixed some usages of Param's warning, that would break on Param 2.0.
> Prepare for Param 2.0

- .github/workflows/test.yaml
Cancel concurrent jobs to avoid bogging down CI across the holoviz org.
> Cancel concurrent test workflows

- hvplot/util.py
This allows to see which package(s) out of cartopy, geoview and pyproj are missing.
> separate import tests to see what's missing

- hvplot/interactive.py
- hvplot/tests/testinteractive.py
- hvplot/util.py
In bokeh 3 our existing interactive `.layout` implementation will not work correctly and is also overly complex so while we maintain backward compatibility we ship both and new layouts.
> Implement bokeh3 compatible layout

- hvplot/converter.py
https://github.com/holoviz/hvplot/pull/1053 forced `geo=True` if tiles were provided. This is not intended as you can use tiles provided by HoloViews and now no longer can.
> Do not force geo=True if tiles are provided

- hvplot/converter.py
Old:
`ImportError: In order to use datashading features the Datashader library must be available. It can be installed with:
conda install -c pyviz datashader`
New:
`ImportError: In order to use datashading features the Datashader library must be available. It can be installed with:
conda install datashader`
Same for GeoViews
> Suggest to install datashader and geoviews from defaults

- hvplot/converter.py
- hvplot/tests/testoperations.py
Alongside https://github.com/holoviz/holoviews/pull/5751
```python
import holoviews as hv
hv.extension('bokeh')
df = pd.DataFrame(
{
"time": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
"value": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
"by": ["d", "d", "d", "a", "a", "b", "b", "b", "b", "b"],
}
)
df.hvplot(
x="time",
y="value",
by="by",
rasterize=True,
color_key="RdBu_r"
)
```
colorbar is not yet supported in HoloViews.
> Support plots that use `by` with `rasterize` with hv.ImageStack

- hvplot/converter.py
- hvplot/tests/testgeo.py
```python
import panel as pn
ds = xr.tutorial.open_dataset("air_temperature").isel(time=0)
plot = ds.hvplot("lon", "lat", features=["land", "borders", "coastline"])
plot
```
--
> Fix underlaying / overlaying features

- examples/user_guide/Timeseries_Data.ipynb
- hvplot/converter.py
Follow-up on https://github.com/holoviz/hvplot/pull/1128 with minor docs improvements, indications that HoloViews >= 1.16 is required and handling of `autorange` when older versions are used with a warning.
> Improve `autorange` docs

- doc/index.md
- examples/user_guide/Introduction.ipynb
- hvplot/polars.py
- hvplot/tests/plotting/testcore.py
- hvplot/tests/testpatch.py
- setup.py
resolves https://github.com/holoviz/hvplot/issues/1023
This adds a simple Polars support to hvplot by converting it to a Pandas DataFrame before putting it into the machinery of hvplot. I'm trying to convert only the necessary columns for the  DataFrame and LazyDataFrame. 
Using the API as described [here](https://pola-rs.github.io/polars/py-polars/html/reference/api.html).
``` python
import hvplot.polars  # noqa
import polars as pl
from bokeh.sampledata.autompg import autompg
df = pl.DataFrame(autompg)
s = df.select("mpg").to_series()
ldf = df.lazy()
type(df), type(s), type(ldf)
df.hvplot(y="cyl")
s.hvplot()
ldf.hvplot.scatter()
```
> Add simple polars support

- examples/conftest.py
- examples/user_guide/Plotting.ipynb
- examples/user_guide/Plotting_with_Matplotlib.ipynb
- examples/user_guide/Plotting_with_Plotly.ipynb
The plotting tests began to fail yesterday: https://github.com/holoviz/hvplot/actions/runs/6802887790
This is likely because a new numba version was released on conda-forge, which also updated the numpy version. (red=failing test, green=passing test)
@maximlt, you can change the code to your liking. This is mostly to get the ball rolling.
>  Rename amin and amax to min and max 

- hvplot/ui.py
Tweaks to labels, placeholders, margins, layout of explorer, based on the minor issues listed here:
https://github.com/holoviz/hvplot/issues/1190
> Fix minor issues in explorer

- examples/user_guide/Interactive.ipynb
- hvplot/interactive.py
This is not major and should be straightforward.
I hope it is fine to create a PR to such a simple fix.
The explanation in the tutorial originates from this discussion.
https://discourse.holoviz.org/t/why-is-the-multiselect-rendered-twice-and-the-chart-only-once/6286/3
I noticed the typo while looking for extra arguments in `interactive()`
> fix typo in the docstring and an explanation for `interactive.panel()` and `interactive.widgets()`

- hvplot/ui.py
Condenses the widget box so there's more space for the plot. Will address the time slider in another PR.
Builds on top of https://github.com/holoviz/hvplot/pull/1197 and partially addresses https://github.com/holoviz/hvplot/issues/1190
Changes based on discovery in https://github.com/holoviz/panel/issues/5856
> Limit explorer widget width

- hvplot/plotting/__init__.py
- hvplot/util.py
hvplot already supports Polars (thank, well done 🙌  🙏 🥳 )
Fancy making `hvPlotTabularPolars` available in the toplevel `plot` function, so that a plotting backend functionality could be considered for Polars too?
> support polars in hvplot.plot method

- hvplot/converter.py
- hvplot/tests/plotting/testohlc.py
Addresses https://github.com/holoviz/hvplot/issues/1214
```python
df = pd.DataFrame({
"Open": [100.00, 101.25, 102.75],
"High": [104.10, 105.50, 110.00],
"Low": [94.00, 97.10, 99.20],
"Close": [101.15, 99.70, 109.50],
"Volume": [10012, 5000, 18000],
}, index=[pd.Timestamp("2022-08-01"), pd.Timestamp("2022-08-03"), pd.Timestamp("2022-08-04")])
ohlc_cols = ["Open", "High", "Low", "Close"]
df.hvplot.ohlc(y=ohlc_cols, hover_cols=["Volume"])
```
> Respect hover_cols for OHLC

- hvplot/tests/testui.py
- hvplot/ui.py
Builds on top of https://github.com/holoviz/hvplot/pull/1198 for more screen space for the plot and partially addresses https://github.com/holoviz/hvplot/issues/1190
> Move plot widget to bottom

- hvplot/plotting/__init__.py
- hvplot/plotting/core.py
- hvplot/polars.py
- hvplot/tests/testplotting.py
Follow-up of  to add a simple test and to avoid registering the hvplot accessor, as I don't think this was intended.
> Polars in hvplot.plot: avoid registering the hvplot accessor and simple test

- examples/user_guide/Geographic_Data.ipynb
Fixes https://github.com/holoviz/hvplot/issues/1185
> Doc: indicate that stamen tiles require a stadia account

- hvplot/ui.py
Addressing (a tiny) part of https://github.com/holoviz/hvplot/issues/1190 with a different take compared to https://github.com/holoviz/hvplot/pull/1200 whose goal is to cover all kind of exceptions the explorer might raise, while in this PR I focused on finding the best way to let them know they should install GeoViews to enable the geo controls.
I ended up trying to import geoviews on initialization and if that fails disabling all the geo controls:
The `Checkbox` widget has no tooltip so instead I used a Toggle with a label that is updated to indicate GeoViews is required.
Trying to instantiate an explorer by passing geo kwargs (e.g. `df.explorer(geo=True)`) will raise an import error.
> Explorer: disable the geo controls when geoviews is not installed

- examples/getting_started/explorer.ipynb
- examples/user_guide/Explorer.ipynb
- hvplot/tests/testui.py
- hvplot/ui.py
Addresses https://github.com/holoviz/hvplot/issues/886
> Explorer: change default plot type from `line` to `scatter`

- examples/user_guide/Plotting_with_Matplotlib.ipynb
Addresses https://github.com/holoviz/hvplot/issues/868, basically reverting https://github.com/holoviz/hvplot/pull/852.
> Doc: reintroduce colorbars in the matplotlib guide

- hvplot/utilities.py
Addresses https://github.com/holoviz/hvplot/issues/685 by extending `show` to display Panel objects (as sometimes hvPlot calls return Panel objects).
> Extend show to display Panel objects

- hvplot/converter.py
- hvplot/tests/testoperations.py
Fixes https://github.com/holoviz/hvplot/issues/1210
This is basically take 2 of https://github.com/holoviz/hvplot/pull/843 that complete the original implementation of https://github.com/holoviz/hvplot/pull/759. Without this fix, a list of 1 `y` variable is assimilated as a categorical.
> Fix considering plots with one y variable as categorical

- doc/index.md
- doc/roadmap.md
I feel that without some sort of roadmap, hvPlot's development is only driven by whatever other development happens in the HoloViz ecosystem and outside, while its development should be more deliberate to gain more momentum.
So I'm suggesting this tentative, ambitious, and subjective (of course) roadmap for hvPlot for 2024. I'm not sure where the roadmap should eventually live If we manage to agree on its content. I'm opening this PR for others to be able to comment on it.
> Add roadmap for 2024

- hvplot/tests/plotting/testcore.py
- hvplot/tests/testcharts.py
- hvplot/tests/testinteractive.py
- hvplot/tests/testoperations.py
- hvplot/tests/testplotting.py
- hvplot/tests/util.py
- Vendoring some of the `make<>` private testing utilities that were removed in Pandas 2.2
- Update a test to remove a FutureWarning
> Compatibility with Pandas 2.2

- README.md
The link to the hvplot_collage.png file was broken, this file was located in the HoloViz blog before it was overhauled. The README already has a decent amount of images.
> Remove the Examples section from the README

- hvplot/tests/plotting/testcore.py
Hey - just wanted to suggest this as a "sister PR" to https://github.com/pola-rs/polars/pull/13238
Then, we could be confident that the "Polars 🤝 hvPlot" compatibility stays stable?
> add downstream polars test

- hvplot/plotting/core.py
- hvplot/tests/testplotting.py
- setup.py
> correctly fall back to all numeric polars cols when y is not specified

- doc/governance/project-docs/MEMBERS.md
Andrew has a long track of contributions to [hvPlot](https://github.com/holoviz/hvplot/pulls?q=is%3Apr+is%3Aclosed+author%3Aahuang11) (and [HoloViews](https://github.com/holoviz/holoviews/pulls?q=is%3Apr+is%3Aclosed+author%3Aahuang11)), dating back to 2018, with an increased activity since October 2023. His background in climate science helps bring some useful domain knowledge, his coding is sharp and he's a pleasure to work with.
I'm calling a vote to promote him to a well-deserved Maintainer role. @philippjfr @Hoxbro this PR will be merged when we all approve it.
> Promote Andrew (@ahuang11) as a Maintainer

- examples/user_guide/Geographic_Data.ipynb
A user brought this to my attention and mentioned that it was hard to figure out crs and projection.
Turns out the section `Declaring an output projection` was hidden under Spatialpandas
This fixes it by reducing the heading of Spatialpandas from `##` to `###`, moving "Declaring an output projection" under "Declaring an output projection".
Lastly, it clarifies the role of crs / projection and adds `projection` to the missing geographic options
> Clarify CRS and output projection

- doc/user_guide/Customization.ipynb
- doc/user_guide/Geographic_Data.ipynb
- hvplot/converter.py
- hvplot/tests/testgeo.py
Addresses https://github.com/holoviz/hvplot/issues/1293
An alternative implementation might have been overloading `tiles` to accept a dictionary like `{"tiles": "ESRI", "alpha": 0.5}`. Interested in what other maintainers think about the two different approaches.
> Add `tiles_opts` parameter to customize the tiles

- hvplot/utilities.py
Fixes https://github.com/holoviz/hvplot/issues/796
`hvplot.save` was an alias for `holoviews.util.save` except that hvPlot sometimes creates Panel objects which the HoloViews function couldn't save. So we delegate to `<pn_obj>.save`. I also thought about just raising a clear error message but thought it'd make everyone's life simpler if it just worked directly. The real fix would be for hvPlot to no longer create Panel objects, but that's another issue.
> Fix saving Panel objects with `hvplot.save`

- .gitignore
- doc/conf.py
- doc/user_guide/Large_Timeseries.ipynb
- doc/user_guide/Timeseries_Data.ipynb
- doc/user_guide/index.md
supersedes https://github.com/holoviz/hvplot/pull/1205
This adds a notebook that explains the different ways of working with large time-series datasets with holoviz
> Add user guide for working with large time-series datasets

- hvplot/converter.py
- hvplot/tests/testoperations.py
fixes #1312
This pull request updates the handling of the `downsample` parameter in hvPlot. Previously, the parameter only accepted a boolean value. With these changes, users can now specify the downsampling algorithm directly, provided they have 'tsdownsample' library installed.
```python
"""
downsample (default=False):
Controls the application of downsampling to the plotted data,
which is particularly useful for large timeseries datasets to
reduce the amount of data sent to browser and improve
visualization performance. Requires HoloViews >= 1.16. Additional
dependencies: Installing the `tsdownsample` library is required
for using any downsampling methods other than the default 'lttb'.
Acceptable values:
- False: No downsampling is applied.
- True: Applies downsampling using HoloViews' …
```
> Allow algorithm as str input to `downsample` operation

- hvplot/converter.py
- hvplot/tests/testcharts.py
Observed while reviewing https://github.com/holoviz-topics/examples/pull/376.
Before:
After:
> Fix setting `group_label` when plotting a hist

- doc/user_guide/Geographic_Data.ipynb
- envs/py3.10-tests.yaml
- envs/py3.11-docs.yaml
- envs/py3.11-tests.yaml
- envs/py3.12-tests.yaml
- envs/py3.8-tests.yaml
- envs/py3.9-tests.yaml
- hvplot/converter.py
- hvplot/tests/testgeo.py
- hvplot/tests/testgeowithoutgv.py
- pyproject.toml
Implements https://github.com/holoviz/hvplot/issues/1289
And also refactors the geographic guide to start by introducing the `tiles=True` usage without GeoViews installed, since this was not documented but is used a few times on examples.holoviz.org.
> Add support to `xyzservices` tiles

- doc/reference/tabular/area.ipynb
- doc/user_guide/Customization.ipynb
- hvplot/converter.py
- hvplot/tests/testoptions.py
Implements https://github.com/holoviz/hvplot/issues/636
@droumis FYI I have noticed that the converter `__init__` signature does not include this kind of plot options passed down to HoloViews. Perhaps they should be added to the signature to later be included in some API reference docs.
> Allow to set the background color with `bgcolor`

- .git-blame-ignore-revs
- This file will be picked up by default by GitHub
- Run `git config blame.ignoreRevsFile .git-blame-ignore-revs` locally
> Make it easier to let git blame ignore some commits

- doc/conftest.py
- envs/py3.10-tests.yaml
- envs/py3.11-docs.yaml
- envs/py3.11-tests.yaml
- envs/py3.12-tests.yaml
- envs/py3.8-tests.yaml
- envs/py3.9-tests.yaml
- hvplot/tests/testfugue.py
- pyproject.toml
fugue 0.9.0 no longer ships with the SQL deps required to run our tests. It's easy to pip install with `pip install fugue[sql]` but there's no equivalent conda way to do so, so for now the sql deps are listed explicitly.
> Fix conda tests

- hvplot/converter.py
- hvplot/tests/testcharts.py
Closes https://github.com/holoviz/hvplot/issues/1094
```
df = pd.DataFrame(
{'City': ['Buenos Aires', 'Brasilia', 'Santiago'],
'Country': ['Argentina', 'Brazil', 'Chile'],
'Latitude': [-34.58, -15.78, -33.45],
'Longitude': [-58.66, -47.91, -70.66]})
df.hvplot.labels("Longitude", "Latitude", "City", by="City")
```
> Support labels by

- hvplot/converter.py
- hvplot/tests/testgeo.py
If geometry is None, it crashes:
```python
import censusdis.data as ced
from censusdis.datasets import ACS5
from censusdis.counties.washington import KING
from censusdis.states import WA
GROUP = "B25008"
gdf_king = ced.download(
ACS5,
2020,
group=GROUP,
state=WA,
county=KING,
tract="*",
with_geometry=True,
remove_water=True,
)
gdf_king
```
> Fix geopandas type check

- hvplot/converter.py
- hvplot/tests/testcharts.py
- hvplot/tests/testoptions.py
- hvplot/tests/testpanel.py
- hvplot/tests/testpatch.py
- hvplot/tests/testutil.py
Fixes https://github.com/holoviz/hvplot/issues/1361
Also:
- Cleans up some imports in the test suite, since pandas and panel are direct dependencies of hvPlot their import doesn't need to be guarded
- Update some test code to HoloViews 1.19
> Ensure date sorting of multi index Pandas dataframes

- doc/conftest.py
Because of https://github.com/pydata/xarray/pull/9182 which has been merged but not yet released.
> Conditionally skip testing the Gridded data user guide

- .github/workflows/docs.yaml
- .github/workflows/test.yaml
- envs/py3.10-tests.yaml
- envs/py3.11-docs.yaml
- envs/py3.11-tests.yaml
- envs/py3.12-tests.yaml
- pyproject.toml
With the latest dev releases of GeoViews we are now pulling in Bokeh 3.5, making the CI fail because of the removal of `bokeh sampledata`.
> Use bokeh_sampledata in CI

- .github/workflows/test.yaml
- envs/py3.10-tests.yaml
- envs/py3.11-tests.yaml
- envs/py3.12-tests.yaml
- envs/py3.9-tests.yaml
- pyproject.toml
See https://pytest-xdist.readthedocs.io/en/latest/distribution.html#running-tests-across-multiple-cpus
> Use psutil logical for test examples

- doc/user_guide/Customization.ipynb
- doc/user_guide/Geographic_Data.ipynb
- hvplot/converter.py
- hvplot/tests/testgeo.py
- hvplot/tests/testgeowithoutgv.py
- hvplot/tests/testgridplots.py
Closes https://github.com/holoviz/hvplot/issues/1375
Will add tests next week if this logic is ok.
Basically if user sets `geo=True` without crs/projection, it does a `pseudo-geo` (i.e. perform projection and toggle off)
> Automatically convert lonlat to xy when tiles=True

- hvplot/tests/testui.py
- hvplot/ui.py
Closes https://github.com/holoviz/hvplot/issues/1406
Adds a warning and checks if kind == curve to prevent random sampling; only sample head.
> Warn on imposing max rows and fix for curve

- hvplot/plotting/core.py
> PERF: Remove Polars PerformanceWarning

- hvplot/tests/testui.py
Observed here: https://github.com/conda-forge/hvplot-feedstock/pull/30
> test: Mark `test_explorer_geo_revise_kind` with geo marker

- README.md
Also, remove the mention of Jupyterlab 2 and below, as Jupyterlab 3 was released on Christmas Eve, 2020.
> docs: Update image links in README

- doc/user_guide/Customization.ipynb
- doc/user_guide/Geographic_Data.ipynb
- hvplot/converter.py
- hvplot/tests/testgeowithoutgv.py
- hvplot/util.py
Closes https://github.com/holoviz/hvplot/issues/1431
```python
import dask.dataframe as dd
import hvplot.dask  # noqa
data = {"x": [-9700947, -9584977], "y": [3890186, 3824923]}
df = dd.from_pandas(pd.DataFrame(data), npartitions=2)
df.hvplot.points("x", "y", tiles=True)
```
> Fix dask tiles regression

- hvplot/networkx.py
- hvplot/tests/testnetworkx.py
Fixes #1437
Tested locally and it appears to work
> Fix hover tooltips for NetworkX plots

- doc/conf.py
- envs/py3.11-docs.yaml
- pyproject.toml
To display the interactivity warning message on pages built from a Notebook or executable Markdown.
> doc: add nb_interactivity_warning extension

- .github/workflows/test.yaml
See failing test here: https://github.com/holoviz/hvplot/actions/runs/11600853910/job/32302285188
> ci: Fix failing CI

- hvplot/converter.py
- hvplot/tests/testcharts.py
- hvplot/util.py
fixes #1461 where the use of matplotlib colormap objects as `cmap` argument results in "TypeError: argument of type 'LinearSegmentedColormap' is not iterable...."
```python
import hvplot.xarray  # noqa
from matplotlib import colormaps
ds = xr.tutorial.open_dataset("air_temperature")
da = ds.air.isel(time=0)
da.hvplot.image(cmap=colormaps['viridis'])
```
> Check cmap type before comparing to categories

- hvplot/converter.py
- hvplot/tests/testui.py
- hvplot/tests/testutil.py
- hvplot/ui.py
- hvplot/util.py
Even though `geo=False`, explorer would raise `raise ImportError('GeoViews must be installed to enable the geographic options.')`
```python
df = pd.DataFrame({'a': [1,2,3], 'b': [4,5,6]})
df.hvplot.explorer(geo=False)
```
Not sure how to add a test for this because the dev dependencies installs geoviews.
> Fix logic for no geoviews explorer

- envs/py3.10-tests.yaml
- envs/py3.11-docs.yaml
- envs/py3.11-tests.yaml
- envs/py3.12-tests.yaml
- envs/py3.9-tests.yaml
- pyproject.toml
intake-xarray 2.0 has been released, see https://pypi.org/project/intake-xarray/#history
Failing the current examples on conda.
> compat: Add upper pin for intake-xarray

- doc/conf.py
- doc/releases.md
And remove the announcement banner for 0.11.
> Add release notes for v0.11.2

- doc/conftest.py
- envs/py3.10-tests.yaml
- envs/py3.11-docs.yaml
- envs/py3.11-tests.yaml
- envs/py3.12-tests.yaml
- envs/py3.9-tests.yaml
- hvplot/tests/conftest.py
- pyproject.toml
It breaks the test suite and is blocking the migration to pixi. Downstream not supporting it yet (datashader, spatialpandas, etc.).
> Pin dask<2025.1.0

- doc/index.md
- doc/user_guide/Large_Timeseries.ipynb
- doc/user_guide/Plotting.ipynb
- doc/user_guide/Plotting_with_Matplotlib.ipynb
- doc/user_guide/Plotting_with_Plotly.ipynb
> Removed 'Home' from website index and replace hide-cell with remove-cell

- hvplot/tests/testplotting.py
- pyproject.toml
Fixes https://github.com/holoviz/hvplot/issues/1483
When a plotting backend is configured on pandas via e.g. `pd.options.plotting.backend =  '<backend>'`, Pandas has two ways to use it:
1. it will try to see if it is registered as an entry point and if so will load the registered module (`holoviews = "hvplot:plotting"` registers `holoviews` as an entry point pointing to the `hvplot.plotting` module).
2. if 1/ doesn't succeed, it will load the module as is
In both cases, the only check Pandas performs is to verify that the backend has a `plot` attribute.
https://github.com/holoviz/hvplot/pull/347 exposed the `plot` function from `hvplot.plotting` in the top-level module, allowing users to register the backend with `pd.options.plotting.backend = 'hvplot'` (leveraging 2/). However, that is …
> Fix calling special Pandas plotting methods with the hvplot backend

- .github/workflows/nightly_lock.yaml
This PR modifies the `nightly_lock` workflow to exclude forks of the repository. See https://github.com/holoviz/holoviews/pull/6507
> modify nightly lock workflow to exclude forks

- hvplot/converter.py
- hvplot/tests/plotting/testohlc.py
```python
import hvplot.pandas  # noqa
from bokeh.sampledata import stocks
df = pd.DataFrame(stocks.AAPL)
df['date'] = pd.to_datetime(df.date)
df.iloc[-50:].hvplot.ohlc(grid=True)
```
> Set OHLC x-axis tooltip to datetime format

- hvplot/__init__.py
- hvplot/converter.py
fixes #1513 
fixes #1506
This PR:
1. **Data Options**: Options for organizing, grouping, and transforming the dataset before visualization, including labels, sorting, and indexing.
2. **Geographic Options**: Configuration options for geographic plots, including map projections, tile overlays, and geographic features like coastlines and borders.
3. **Size and Layout options**: Customization options for plot sizes and overall layout, including responsive mode.
4. **Axis Options**: Customization options for axis appearance and behavior, including labels, limits, tick formatting, and axis scaling.
5. **Grid and legend options**: Options for setting the grid or legend of plots as well as colorbar options.
6. **Interactivity options**: Bokeh specific options for adding hover tools as well as …
> Re-categorize HoloViewsConverter docstring and add missing keywords in the correct special lists

- hvplot/converter.py
- hvplot/plotting/core.py
> Document the `stacked` docstring directly in the relevant methods

- hvplot/converter.py
fixes #1507
The PR documents the remaining keywords used internally in the HoloViewsConverter class.
> Document extra keywords caught internally

- doc/_ext/plotting_options_table.py
- doc/conf.py
- doc/developer_guide.md
- doc/index.md
- doc/ref/index.md
- doc/ref/plot_options/data.ipynb
- doc/ref/plot_options/index.md
- hvplot/converter.py
- pixi.toml
- pyproject.toml
This PR adds a new `Reference` top-level section (folder is called `ref` as `reference` is already taken by the Reference Gallery) that for now includes this:
- Plot Options
- Data options
The Plot Options page includes a table per options group (e.g. `Data Options`, `Resampling Options`). These tables are automatically built from the class docstring of the `HoloViewsConverter` object. This is done via a custom Sphinx extension that leverages `numpydoc` to parse the docstring. To get the table to format the content nicely, I had to touch the docstrings in a few places. Ultimately, we should enable some sort of docstring validation to make sure it is appropriately formatted.
The Data Options page is mostly a placeholder at the moment (for future PRs). While the Plot Options page only …
> Automatically document the generic plot options

- hvplot/tests/conftest.py
- hvplot/tests/testhelp.py
- hvplot/tests/testoverrides.py
- hvplot/tests/testui.py
- hvplot/ui.py
With one small code change in the explorer, avoiding passing `opts` to the converter as `opts` is not a kwarg the converter knows about.
> Run unit tests with param warnings as exceptions by default

- .github/workflows/docs.yaml
This is to test the Github interface with this flag for https://github.com/holoviz/hvplot/pull/1533. It can always be reverted.
> Add version as input for docs versioning

- doc/ref/deprecations.md
- doc/ref/index.md
- hvplot/converter.py
- hvplot/tests/testdeprecations.py
Resolves https://github.com/holoviz/hvplot/issues/1512
- Already at the `FutureWarning` level as this was an entirely undocumented argument
- Added a `deprecations.md` like on Param (hvPlot will need to deprecate stuff to prepare for 1.0 so that will be useful)
> Deprecate the debug argument

- doc/ref/deprecations.md
- hvplot/converter.py
- hvplot/plotting/__init__.py
- hvplot/tests/testdeprecations.py
- hvplot/util.py
Resolves https://github.com/holoviz/hvplot/issues/1492
This function is originally designed to be the entry point for the Pandas plotting backend (i.e. when setting `pd.options.plotting.backend = 'hvplot'` and calling `df.plot(...)`). We don't recommend using this function directly.
> Deprecate handling DuckDB objects in the plot function

- hvplot/plotting/andrews_curves.py
- hvplot/tests/plotting/testandrewscurves.py
Fixes https://github.com/holoviz/hvplot/issues/1549
1. Ensures the x-axis is between -pi and pi as it is how Andrews curves are usually plotted
2. Modify the first coefficient to be `1/sqrt(2)` since this is what is described in the docstring
On 2), different types of transforms can be used to create Andrews curves and it could be the implementation corresponded with a valid type, however this didn't match with the docstring, and the one with this coefficient is the canonical one.
> Minor fixes to Andrews Curves

- .github/workflows/auto_triage.yml
fixes #1581 
This PR add a GitHub action tool that automatically labels every new issue as `TRIAGE` regardless of how it was created.
Tested via:
1. [Web UI](https://github.com/Azaya89/hvplot/issues/6)
2. [GH CLI](https://github.com/Azaya89/hvplot/issues/7)
> Add auto-label action

- .github/workflows/test.yaml
- pixi.toml
Thought it'd be useful given the converter code is "a big `if` statement". Global coverage will go down by about 2% based on local testing with branch coverage enabled.
> Enable branch coverage

- doc/ref/plotting_options/grid_legend.ipynb
- doc/ref/plotting_options/index.md
fixes #1575 
This PR adds the Grid and Legend options to the reference docs.
> Document Grid and Legend Options

- hvplot/converter.py
- hvplot/tests/testcharts.py
Resolves https://github.com/holoviz/hvplot/issues/1313
Setting `logx` or `loglog` to `True` plots the histogram bin edges on a log10 scale (new) and plots the x-axis with a log scale (not new). This is different from Pandas, which plots the data on an x-axis log scale. I think it's a better default.
```python
import numpy as np, polars as pl
import hvplot.polars
rng = np.random.default_rng(seed=123)
df = pl.DataFrame({
"x": 10. ** rng.standard_normal(size=100)
})
df.hvplot.hist(logx=True)
```
> Add support for log10 binning for histograms with logx and loglog

- doc/conf.py
- doc/ref/plotting_options/geographic.ipynb
- doc/ref/plotting_options/index.md
- doc/ref/plotting_options/resampling.ipynb
- doc/ref/plotting_options/streaming.ipynb
- doc/ref/plotting_options/styling.ipynb
- hvplot/converter.py
The resampling options notebook depends on https://github.com/holoviz/hvsampledata/pull/34 being merged and released.
Note to self: I found the rasterize/datashade + categorical experience to be quite a bit of a mess and in need of somehow going through all the combinations of options possible and streamlining their behavior/output.
> Document resampling, geographic, and streaming options

- doc/gallery/statistical/violin.ipynb
Couldn't figure out how to do no fill alpha for matplotlib, also had to use the numpy way to jitter mpl.
> Add violin with scatter

- doc/ref/plotting_options/styling.ipynb
- hvplot/converter.py
- hvplot/tests/testoptions.py
Useful for further customization of Bokeh and Matplotlib plots without having to directly interact with their objects.
```python
import hvplot.pandas  # noqa
df = hvplot.sampledata.penguins("pandas")
plot = df.hvplot.scatter(
x="bill_length_mm", y="bill_depth_mm", color="black",
backend_opts={
"plot.xgrid.grid_line_color": "grey",
"plot.xgrid.grid_line_dash": "dotted",
"plot.xaxis.axis_label_text_font_style": "bold",
"plot.yaxis.axis_label_text_font_style": "bold",
"hover.attachment": "vertical",
}
)
plot
```
> Add the backend_opts option

- doc/ref/plotting_options/legend.ipynb
- doc/ref/plotting_options/styling.ipynb
- hvplot/converter.py
- hvplot/tests/testoptions.py
This adds two useful options to configure the legend with `legend_cols` to specify the number of columns and `legend_opts` to enable advanced legend styling.
```python
import hvplot.pandas  # noqa
df = pd.DataFrame({"y": np.random.random(20), "cat": list(map(chr, range(97, 117)))})
df.hvplot.scatter(
by="cat", height=250, legend_cols=3,
legend_opts={"background_fill_alpha": 0.2, "background_fill_color": "grey"}
)
```
> Add legend_cols and legend_opts options

- doc/_static/switcher.json
I forgot to update switcher.json before the release 🙃. I launched a main docs build from this branch and that worked well.
> Update the docs switcher
