holoviz/hvplot

README.md, conda.recipe/meta.yaml, doc/about.rst, doc/conf.py, doc/getting_started/index.rst, doc/index.rst
This part is ready to merge, but I haven't yet looked at the notebooks, and will probably have changes there too.
=> Misc edits

examples/user_guide/Display_and_Saving.ipynb, examples/user_guide/Plotting_API.ipynb, examples/user_guide/Streaming_Plots.ipynb, examples/user_guide/XArray_Plotting.ipynb, holoplot/__init__.py, holoplot/converter.py, holoplot/dask.py, holoplot/pandas.py, holoplot/streamz.py, holoplot/xarray.py
=> Review cleanup

environment.yml, examples/user_guide/Introduction.ipynb, examples/user_guide/Plotting.ipynb, holoplot/__init__.py, holoplot/converter.py, holoplot/intake.py
Provides better consistency with pandas API. Main changes:
To do:
=> API consistency changes

holoplot/__init__.py, holoplot/converter.py, holoplot/tests/testcharts.py, holoplot/tests/testoverrides.py, holoplot/util.py
=> Add improved geographic support

holoplot/converter.py
Ensures that x/y argument does not clash with groupby.
=> Improvements for x/y and groupby interaction

README.md, doc/homepage.ipynb, doc/user_guide/index.rst, environment.yml, examples/user_guide/Geographic_Data.ipynb, holoplot/__init__.py, holoplot/converter.py, holoplot/util.py, holoplot/xarray.py, setup.py
Improves support for geographic plots and adds user guide.
=> Improved support for geographic plots

holoplot/converter.py
=> Minor fixes and enhancements

holoplot/converter.py
=> Added support for cumulative histogram and explicit bins

environment.yml, examples/user_guide/Plotting.ipynb, hvplot/converter.py, hvplot/util.py, setup.py
=> Various fixes

hvplot/converter.py, hvplot/tests/testoperations.py
=> Got x_sampling and y_sampling hooked up for rasterize/datashade

doc/homepage.ipynb
=> Add "on" to "miss out the benefits".

hvplot/__init__.py
=> Dropped import of IPython display function

hvplot/__init__.py
=> Add docs for default hvplot method

examples/user_guide/Plotting.ipynb, hvplot/converter.py
The ``legend`` option now allows either True/False (keeping current behavior) or a valid holoviews legend_position.
Any thoughts @jsignell? I prefer this to introducing a separate legend_position option but you might have a different preference.
=> Allow customizing legend position

hvplot/__init__.py, hvplot/intake.py
=> Handle non-IPython environments

hvplot/converter.py, hvplot/tests/testgridplots.py
=>  Fixed bug handling DataArray in RGB plots

hvplot/__init__.py, hvplot/converter.py, hvplot/tests/testgridplots.py, hvplot/util.py, setup.py
=> Improved handling of groupby dimensions on RGB

hvplot/converter.py
=> Fixes for labelled property

hvplot/converter.py
=> Allow defining style cycles as lists

hvplot/converter.py, hvplot/tests/testcharts.py
=> Ensure setting legend changes legend position

.appveyor.yml
Might need to add conda-forge as a channel. Not at all sure why this isn't triggering a build.
=> Adding appveyor config file

README.md
Not sure if you'll want the coverage row in there.
=> New style readme [skip ci]

README.md
After this comment: https://github.com/pyviz/hvplot/pull/160#issuecomment-462443779
=> Adding "About PyViz" to the readme

hvplot/converter.py
Because I spent half an hour being dumbfounded why coastlines weren't showing even though the lats and lons were within bounds!
=> If line or scatter, warn that it will not project

examples/user_guide/Customization.ipynb, hvplot/converter.py
Fixes https://github.com/pyviz/hvplot/issues/163
=> Make xsampling/ysampling -> x_sampling/y_sampling

hvplot/__init__.py, hvplot/converter.py
=> Add errorbars

hvplot/converter.py, hvplot/tests/testcharts.py
=> Let holoviews set defaults for points

hvplot/__init__.py, hvplot/converter.py
https://github.com/pyviz/hvplot/issues/224
```
import holoviews as hv
from holoviews import dim, opts
hv.extension('bokeh')
xs, ys = np.arange(0, 2 * np.pi, .2), np.arange(0, 2 * np.pi, .2)
X, Y = np.meshgrid(xs, ys)
U = np.cos(X)
V = np.sin(Y)
mag = np.sqrt(U**2 + V**2)
angle = (np.pi/2.) - np.arctan2(U/mag, V/mag)
ds = xr.merge([
xr.DataArray(mag, dims=('x', 'y'), coords={'x': xs, 'y': ys}, name='mag'),
xr.DataArray(angle, dims=('x', 'y'), coords={'x': xs, 'y': ys}, name='angle')
])
hv.VectorField(ds, ['x', 'y'], ['angle', 'mag'])
ds.hvplot.vectorfield('x', 'y', 'angle', 'mag').opts(width=300)
```
=> Plot vectorfield

hvplot/converter.py
Fixes https://github.com/pyviz/hvplot/issues/67, https://github.com/pyviz/hvplot/issues/171
=> Consistently warn if plot type does not support geo

hvplot/converter.py, hvplot/tests/testgridplots.py
Closes: #74 
Supersedes: #97 
~~Still working on getting the test working, but just to capture what I've done so far.~~
It'd be nice to add a quadmesh test if possible.
=> Trying to do more sensible defaults for 2D xarrays

hvplot/converter.py, hvplot/tests/testoptions.py
- Fixes https://github.com/pyviz/hvplot/issues/242
=> Fixed handling of logz

hvplot/converter.py, hvplot/tests/testoptions.py
=> Consistently handle dim mappings

hvplot/converter.py, hvplot/tests/testgeo.py
Closes https://github.com/pyviz/hvplot/issues/191
=> Add support for geo hexbin

examples/user_guide/Geographic_Data.ipynb, hvplot/converter.py, hvplot/tests/testgeo.py
=> Add coastline/tiles options

hvplot/converter.py, hvplot/tests/testoperations.py
Fixes https://github.com/pyviz/hvplot/issues/99
=> Improved handling of datashader aggregator

hvplot/converter.py, hvplot/tests/testoptions.py
Closes #265 
This was a regression introduced in #258. I added a test to make sure this doesn't break again.
=> Allow cmap to be list

hvplot/converter.py, hvplot/tests/testgeo.py, hvplot/tests/testoperations.py, hvplot/tests/testoptions.py
Alternative to #268 
Closes: #192 
Closes: #75
=> Alternative implementation to aspect handling

hvplot/converter.py, hvplot/tests/testoperations.py
Closes #267 
Need to think about how to include legend.
=> If cmap is a dict, just pass it through

hvplot/converter.py, hvplot/tests/testcharts.py, hvplot/tests/testgeo.py, hvplot/util.py
I think `hover_cols` had been broken in general actually. 
Closes: #240 
~~This PR doesn't quite work with dask yet. Not sure why.~~
=> Adding the ability to get index on hover

hvplot/converter.py, hvplot/tests/testoptions.py
=> Make glasbey_category10 the default categorical colormap

hvplot/converter.py
=> Fix stats plots ordering

hvplot/converter.py
`row` and `col` were not being taking out of the fields that are considered when choosing default x/y/z. From the Subplots notebook:
=> Fixing up row/col to make behavior match groupby/by

.gitignore, hvplot/.version
I accidentally checked in the version in #258
=> Cleaning up version

hvplot/converter.py
Just some little changes that I made while figuring out what the difference was between `__call__` `__init__` and the methods.
=> Just cleaning the code

hvplot/converter.py, hvplot/tests/testgridplots.py, hvplot/util.py
=> Fix multi z

hvplot/converter.py, hvplot/tests/testgeo.py
=> Coastline sets geo=True by default

hvplot/converter.py, hvplot/tests/testgeo.py
I was surprised that this wasn't already allowed.
=> Allow tiles to be objects as well as strings

examples/reference/pandas/line.ipynb
This is the line plot example we generated at the PyData NYC sprint.
=> Add line plot example

examples/reference/pandas/box.ipynb
This is the box plot example we generated at the PyData NYC sprint.
=> Add a Box Plot Example

doc/developer_guide/index.rst, doc/getting_started/index.rst, doc/index.rst
* 'pyviz/hvplot' -> 'holoviz/hvplot'
* update LICENSE.txt link to holoviz project
=> Update some github links in docs

README.md
Small PR removing the About section from the project's README file.
=> Removing the About section from the README file

doc/about.rst
=> Updating the About Us Section of the hvPlot site

doc/conf.py
@jlstevens @philippjfr 
I added the Google Analytics UA to the conf.py file.
=> Adding Google Analytics

hvplot/converter.py, hvplot/tests/testgridplots.py
Fixes https://github.com/holoviz/hvplot/issues/329
=> Fix inference of non-declared index coordinates

hvplot/utilities.py
Fixes https://github.com/holoviz/hvplot/issues/305
Fixes https://github.com/holoviz/hvplot/issues/352
=> Update save and show utilities

hvplot/converter.py
Ensures that functionality relying on `Dataset.pipeline` (e.g. linked brushing) works with hvPlot output.
=> Preserve Dataset.pipeline

hvplot/networkx.py
Fixes https://github.com/holoviz/hvplot/issues/189
=> Fixed default hover on networkx plots

hvplot/converter.py, hvplot/tests/testcharts.py, hvplot/tests/testoperations.py, hvplot/tests/testoptions.py, hvplot/util.py
Fixes https://github.com/holoviz/hvplot/issues/326
Fixes https://github.com/holoviz/hvplot/issues/358
=> Improved option handling

doc/user_guide/index.rst
Fixes https://github.com/holoviz/hvplot/issues/62
=> Documentation updates

hvplot/converter.py, hvplot/tests/testgridplots.py, hvplot/util.py
Fixes https://github.com/holoviz/hvplot/issues/354
Fixes https://github.com/holoviz/hvplot/issues/399
=> Improved handling of indexes on flattened grid

hvplot/converter.py
Fixes https://github.com/holoviz/hvplot/issues/367
=> Handle by argument for gridded types

hvplot/converter.py, setup.py
Fixes https://github.com/holoviz/hvplot/issues/468
Fixes https://github.com/holoviz/hvplot/issues/469
=> Do not sort overlays

.travis.yml, hvplot/networkx.py
Partially fixes https://github.com/holoviz/hvplot/issues/471
=> Update networkx docstring

setup.py
=> Removes the __main__ console script that doesn't exist.

hvplot/plotting/core.py, hvplot/tests/testoverrides.py
Closes https://github.com/holoviz/hvplot/issues/72 and https://github.com/holoviz/hvplot/issues/517
=> Allow selecting in metadata

hvplot/converter.py
If no explicit color_key is supplied this also supplies the colormap to the color_key argument.
=> Provide color_key to datashade as well as cmap

hvplot/networkx.py
Fixes https://github.com/holoviz/hvplot/issues/521
=> Handle node_shape in networkx

hvplot/converter.py, hvplot/tests/testtransforms.py
Implement https://github.com/holoviz/hvplot/issues/497
=> Add transforms argument

hvplot/converter.py
holoviz/hvplot#423
requires
https://github.com/holoviz/holoviews/pull/4527
=> Hover mode

.github/workflows/test.yaml, hvplot/converter.py
Fixes https://github.com/holoviz/hvplot/issues/327
=> Handle cycles for continuous colormaps

examples/user_guide/Plotting.ipynb, examples/user_guide/Subplots.ipynb
=> Use list of strings rather than bytes

examples/reference/pandas/scatter.ipynb
I learnt how to do this here https://discourse.holoviz.org/t/add-an-extra-field-when-hovering-in-hvplot-scatter/2331 and wanted to contribute back the docs as my reference. I would like to think others would benefit from this example as well
=> add hover_cols example

hvplot/converter.py
Wikipedia is no longer available.
=> Switch default tile source to OSM

hvplot/converter.py
Not done here but it fixes some initial issues with streaming data. Basically the converter applies some basic transforms when you plot a regular dataframe which are not applied to any data arriving through a stream which means that the example data is not processed the same way as the streaming data causing things to break.
=> Apply transforms for streaming data

hvplot/converter.py
Fixes https://github.com/holoviz/hvplot/issues/592
=> Do not plot streamz example point

hvplot/converter.py, hvplot/tests/testcharts.py
Fixes https://github.com/holoviz/hvplot/issues/589
=> Take group_label from columns if available

hvplot/tests/testoperations.py
Fixes https://github.com/holoviz/hvplot/issues/560
=> Skip datashader tests on 32-bit architectures

hvplot/converter.py
Fixes https://github.com/holoviz/hvplot/issues/569
=> Fix passing in multiple z-values

examples/user_guide/Customization.ipynb, hvplot/converter.py
Document clim better and update the customization notebook.
Fixes https://github.com/holoviz/hvplot/issues/559
=> Update customization docs

hvplot/converter.py
Fixes https://github.com/holoviz/hvplot/issues/588
=> Ensure violin and boxplot color is applied

hvplot/interactive.py
Allows:
```python
dfi.iloc[slider.param.value_start:slider.param.value_end]
```
=> Allow using getitem on an accessor in interactive

hvplot/ui.py
Don't want to blow up peoples browser accidentally
=> Limit number of rows displayed by UI at once

CHANGELOG.md, doc/releases.md
Thanks to @jbednar for drafting these!
=> Version 0.7.3 release notes

hvplot/intake.py, hvplot/plotting/scatter_matrix.py, hvplot/tests/testgeo.py, hvplot/tests/testplotting.py, hvplot/util.py
=> Changed to packaging.version

hvplot/ui.py
A number of improvements to ensure plots resize correctly.
=> Improve sizing of hvPlot UI

.github/workflows/test.yaml
Just testing out if we can make the github action builds a bit quicker.
=> CI: Cache conda builds

hvplot/converter.py, hvplot/tests/testcharts.py, hvplot/tests/testgeo.py
Just a quick attempt at fixing https://github.com/holoviz/hvplot/issues/675 although it would probably be better to fix it at the Holoviews level.
=> Wrap color in hv.dim when it matches a dimension/column

.github/workflows/docs.yaml
Failing for an unknown reason, for now.
=> Fix the docs build

.github/workflows/build.yaml, .github/workflows/docs.yaml, .github/workflows/test.yaml
Schedule runs of the tests, docs and builds workflows on Sundays.
=> Schedule workflow runs

hvplot/converter.py, hvplot/tests/testgridplots.py
Fixes https://github.com/holoviz/hvplot/issues/706
=> Ensure zarr based DataArrays are not loaded into memory

hvplot/converter.py, hvplot/util.py
This is no longer required since hvplot dropped support of Python 2.
=> No longer use basestring from holoviews.core.util

hvplot/interactive.py, hvplot/tests/testinteractive.py
=> Add support for accessor in hvplot.interactive

hvplot/__init__.py, hvplot/ui.py
=> Add docstring to hv.bind

hvplot/converter.py
That's a safer approach to avoid modifying the singleton feature exposed by GeoViews.
=> Clone GeoViews' features

examples/user_guide/Plotting_with_Matplotlib.ipynb
Some docs fixes required after checking the last docs build.
=> Minor doc fixes

doc/releases.md
=> Add 0.8.1 release notes

doc/index.md
Fixes https://github.com/holoviz/hvplot/issues/849
=> Add missing A

hvplot/ui.py
=> Update explorer docstring

doc/index.md
Hi, in the backend section, I thought we should also show bokeh since people might not read the document in order.
=> Add bokeh tab

index.html
adds a user survey banner to the top of the page, as a temporary hack.
=> add survey banner

README.md
Some minor changes, including removing the smileys (a bit controversial, I would add them back if this was agreed at the global Holoviz level), removing the support table which contained erroneous data and reshuffling the parts a bit.
=> Small rework of the README

setup.py
I noticed that the pins on conda-forge were different than the ones defined here, this PR aligns them.
=> Update build pins

hvplot/__init__.py, hvplot/pandas.py, hvplot/plotting/core.py
Fixes minor docstring issues discovered while creating this video https://twitter.com/MarcSkovMadsen/status/1596243231733608448?s=20&t=56As_qnUM-vljDr7SKqsFg.
=> docstring fixes

.github/workflows/test.yaml, setup.cfg, setup.py, tox.ini
Resolves #1013
Updated the test suite to not fail and added Python 3.11 to it. Also added python 3.11 as a classifier. 
No code change has been done.
=> Python 3.11 support

.pre-commit-config.yaml, examples/reference/geopandas/polygons.ipynb, examples/reference/pandas/andrewscurves.ipynb, examples/reference/pandas/barh.ipynb, examples/reference/xarray/image.ipynb
To clean up the current and future notebooks...
=> Add clean notebook hook and run it

.github/workflows/build.yaml, .github/workflows/docs.yaml, .github/workflows/test.yaml, .pre-commit-config.yaml, setup.py, tox.ini
Let's see if we're more lucky than a year ago with https://github.com/holoviz/hvplot/pull/718
=> Run examples with nbval

.github/workflows/build.yaml, .github/workflows/test.yaml, setup.py, tox.ini
To fix the build.
EDIT:
Turned into another battle with pyctdev.
=> Add conda-forge and remove bokeh

examples/reference/pandas/scatter.ipynb
In response to this issue: https://github.com/holoviz/hvplot/issues/1117
=> Added extra size parameter to scatter plot example

hvplot/utilities.py
Fix to https://github.com/holoviz/hvplot/issues/1115
Note:  There do not appear to be any existing tests for this method or file.
=> Update show method to return the configured Server or StoppableThread

.pre-commit-config.yaml, doc/releases.md, examples/reference/pandas/errorbars.ipynb, examples/reference/pandas/hist.ipynb, examples/reference/xarray/image.ipynb, examples/user_guide/Customization.ipynb, examples/user_guide/Pandas_API.ipynb, hvplot/__init__.py, hvplot/converter.py, hvplot/interactive.py, hvplot/plotting/core.py, hvplot/plotting/scatter_matrix.py, hvplot/tests/testinteractive.py, hvplot/utilities.py, pyproject.toml
I am adding codespell to pre-commit and fix spelling mistakes.
https://www.grammarly.com/blog/everytime-every-time/
=> Add codespell to pre-commit

hvplot/ui.py
See https://github.com/holoviz/panel/issues/5628#issuecomment-1763443895
=> Fix displaying widgets controlled DynamicMaps in the explorer

doc/conf.py, setup.py
Exactly what the title says :)
=> Setup GoatCounter and remove Google Analytics

hvplot/tests/testui.py, hvplot/ui.py
=> Change default legend loc to preserve screen space

setup.py
Addresses https://github.com/holoviz/hvplot/issues/1019
=> Bump minimum Param version to 1.12.0

doc/conftest.py, hvplot/tests/conftest.py, setup.py
- Install `dask[dataframe]`
- Disable query planning (`melt` not implemented)
=> CI: fix the test suite after the latest Dask release

.github/workflows/test.yaml
=> CI: fix the options of the full matrix

.pre-commit-config.yaml, doc/conf.py, doc/releases.md, doc/user_guide/Large_Timeseries.ipynb, envs/py3.10-tests.yaml, envs/py3.11-docs.yaml, envs/py3.11-tests.yaml, envs/py3.12-tests.yaml, envs/py3.8-tests.yaml, envs/py3.9-tests.yaml, scripts/update_conda_envs.py
- Fix hiding a cell on the new large timeseries notebook
- Add an announcement banner for the release, linking to the blog post
=> Another PR to prepare the release

doc/reference/pandas/paths.ipynb
Closes https://github.com/holoviz/hvplot/issues/1147
=> Add paths reference notebook

hvplot/converter.py, hvplot/tests/testcharts.py
Closes https://github.com/holoviz/hvplot/issues/1100
=> Do not set bin_range if shared_axes=False

doc/user_guide/Plotting.ipynb, doc/user_guide/Plotting_with_Matplotlib.ipynb, doc/user_guide/Plotting_with_Plotly.ipynb
https://github.com/holoviz/holoviews/pull/6391
=> hide Dask warnings on the plotting guides

doc/user_guide/Introduction.ipynb
Resolves: https://github.com/holoviz/hvplot/issues/1399
=> docs: Small section about Ruff's allowed-unused-imports

.pre-commit-config.yaml, doc/user_guide/NetworkX.ipynb, pyproject.toml
Update pre-commit
- Update version
- Removing `nbqa` as this can now be handled by ruff itself (have not enabled formatting for notebooks)
- Format `.pre-commit-config.yaml` with prettier.
=> chore: Update pre-commit

hvplot/converter.py
resolves #1505 
I tried to insert the docstrings in alphabetical order.
=> Document keywords not in the HoloViewsConverter docstring

hvplot/converter.py, hvplot/tests/testoptions.py
Fixes https://github.com/holoviz/hvplot/issues/1442
=> Fix setting xaxis/yaxis

hvplot/converter.py
Closes https://github.com/holoviz/hvplot/issues/1468
=> No longer use some deprecated Param API

.github/workflows/test.yaml, pyproject.toml
Currently, pip tests are failing, which has caused some problems with a failing downstream test for a datashader release.
I have changed the pip test to only run on full, as downstream testing should not have this problem.
=> add hvsampledata to examples

pyproject.toml
To align hvPlot with the other HoloViz packages.
=> Build sdist and wheel with hatchling instead of setuptools

doc/conf.py
This is going to be useful for SEO when the site is versioned.
=> Set the canonical URL

doc/ref/deprecations.md, hvplot/converter.py, hvplot/tests/testdeprecations.py
Resolves https://github.com/holoviz/hvplot/issues/1604
=> Deprecate hover_formatters

hvplot/utilities.py
Fixes https://github.com/holoviz/hvplot/issues/1647
=> enh: Support param.rx with hvplot.show
